// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7vj9-XmsWHkmGiV4LssYQf6aFLj7UxE4',
    appId: '1:779923091804:web:e500bd091a05f03132d199',
    messagingSenderId: '779923091804',
    projectId: 'bloc-firebase-test-696bf',
    authDomain: 'bloc-firebase-test-696bf.firebaseapp.com',
    storageBucket: 'bloc-firebase-test-696bf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv9qHX5Kz1mIyRsrXxD6kFTiCtssXV6aA',
    appId: '1:779923091804:android:8a4560b38926981932d199',
    messagingSenderId: '779923091804',
    projectId: 'bloc-firebase-test-696bf',
    storageBucket: 'bloc-firebase-test-696bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3mhQkZoI7aqYer-iqXK71x40FXMe7YzA',
    appId: '1:779923091804:ios:77f1feaae94f18aa32d199',
    messagingSenderId: '779923091804',
    projectId: 'bloc-firebase-test-696bf',
    storageBucket: 'bloc-firebase-test-696bf.appspot.com',
    iosBundleId: 'com.example.blocFirebaseTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3mhQkZoI7aqYer-iqXK71x40FXMe7YzA',
    appId: '1:779923091804:ios:e1b5d62fd2597b1132d199',
    messagingSenderId: '779923091804',
    projectId: 'bloc-firebase-test-696bf',
    storageBucket: 'bloc-firebase-test-696bf.appspot.com',
    iosBundleId: 'com.example.blocFirebaseTest.RunnerTests',
  );
}
